### ISSUE TITLE
Error While setting up sensor

### ISSUE THREAD

**Issue by graywizardx** [gillesvs/librelink#7]
I get the below error when I try and install the device for the first time.

I have verified that I can see the data in LibreLinkUp and online as well.

I have several other errors about retrieving the data, but they are all roughly the NoneType exception.

`
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:352
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 6:22:41 PM (2 occurrences)
Last logged: 6:31:13 PM

Error while setting up librelink platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 698, in _async_add_entity
    original_icon=entity.icon,
                  ^^^^^^^^^^^
  File "/config/custom_components/librelink/sensor.py", line 199, in icon
    self.coordinator.data[self.index]["glucoseMeasurement"][
TypeError: 'NoneType' object is not subscriptable
`

**Comment by gillesvs** [comment]
Hello @graywizardx ,

Can you activate the debug mode for the integration and send me the log file?
Thanks

**Comment by gillesvs** [comment]
See #10
